### ISSUE TITLE
TypeError: dictUsers.filter is not a function

### ISSUE THREAD

**Issue by cuducos** [zehfernandes/twitter-following-map-obsidian#1]
Hi,

I always wanted to explore some dataviz with Twitter data, so I decided to be a tester here, is that ok?

I'm always getting this error:

```
﻿﻿DEBUG 0 Foone
---------------
TypeError: dictUsers.filter is not a function
    at createDataStructure (/private/tmp/twitter-following-map-obsidian/index.js:110:26)
    at loopFollowers (/private/tmp/twitter-following-map-obsidian/index.js:45:5)
Waiting 900000ms
---------------
DEBUG 0 Foone
---------------
TypeError: dictUsers.filter is not a function
    at createDataStructure (/private/tmp/twitter-following-map-obsidian/index.js:110:26)
    at loopFollowers (/private/tmp/twitter-following-map-obsidian/index.js:45:5)
Waiting 900000ms
---------------
DEBUG 0 Foone
---------------
TypeError: dictUsers.filter is not a function
    at createDataStructure (/private/tmp/twitter-following-map-obsidian/index.js:110:26)
    at loopFollowers (/private/tmp/twitter-following-map-obsidian/index.js:45:5)
Waiting 900000ms
```

Maybe the cache is returning something unexpected? What do you think?

**Comment by zehfernandes** [comment]
Glad to have you as a tester.

The script has two parts. 
1) Get the following users information
2) Loop through each user and find the followers. 

I pushed a change that includes this step. You should be able to run `node index.js` and go through both steps in a single run.

**Comment by cuducos** [comment]
Like a charm 💜
