### ISSUE TITLE
Should we skip protected accounts?

### ISSUE THREAD

**Issue by cuducos** [zehfernandes/twitter-following-map-obsidian#4]
I'm stuck at this error for hours:

```
---------------
DEBUG 64 fernandasabaudo
---------------
Error: Not authorized.
    at Object.exports.makeTwitError (/private/tmp/twitter-following-map-obsidian/node_modules/twit/lib/helpers.js:74:13)
    at onRequestComplete (/private/tmp/twitter-following-map-obsidian/node_modules/twit/lib/twitter.js:344:25)
    at Request.<anonymous> (/private/tmp/twitter-following-map-obsidian/node_modules/twit/lib/twitter.js:364:7)
    at Request.emit (events.js:327:22)
    at Gunzip.<anonymous> (/private/tmp/twitter-following-map-obsidian/node_modules/request/request.js:1076:12)
    at Object.onceWrapper (events.js:421:28)
    at Gunzip.emit (events.js:327:22)
    at endReadableNT (_stream_readable.js:1201:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21) {
  code: null,
  allErrors: [ { request: '/1.1/friends/ids.json', error: 'Not authorized.' } ],
  twitterReply: { request: '/1.1/friends/ids.json', error: 'Not authorized.' },
  statusCode: 401
}
Waiting 900000ms
```

This message is repeated over and over again.

I haven't had the chance to debug it further, but I guess we should skip protected accounts (they might follow the main user, but the main user has no access to its data, right? [`@fernandasabaudo`](https://twitter.com/fernandasabaudo) is a proteced account).

**Comment by zehfernandes** [comment]
Good point. I pushed a fix to only go back in the loop if the code error is the "Rate limit exceeded"

**Comment by cuducos** [comment]
Yay 🎉 
Working… I could see some protected accounts in the logs, and they're not blocking the execution any more : )
